# remove comments to use MAINNET (default: testnet)
#node:
#  url: https://mainnet.aeternity.io
#compiler:
#  url: https://compiler.aeternity.io
#mdw:
#  url: https://mainnet.aeternity.io/mdw
#network: MAINNET

wallet:
  path: /home/user/wallet.json

names:
  #    pointers: # note: the pointers will be used for all names in the watchlist if update is set true
  #      account_pubkey: ak_...
  #      channel: ch_...
  #      contract_pubkey: ct_...
  #      oracle_pubkey: ok_...
  watchlist:
    - name: aeternity.chain
      maxBid: 30000000000000000000  # name will be claimed until maxBid is reached, default: 25000000000000000000
      update: true                  # will extend the nameTtl to max value and set a pointer to the account, default: false
    - name: kryptokrauts.chain

# output to a file
logging:
  file: /var/log/aens-name-claimer.log